packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.22.59
  "@platforma-sdk/ui-vue": ^1.22.59
  "@platforma-sdk/workflow-tengo": ^2.13.3
  "@platforma-sdk/block-tools": ^2.5.15
  "@platforma-sdk/test": ^1.22.63
  "@platforma-sdk/tengo-builder": ^1.17.7
  "@platforma-sdk/package-builder": ^2.15.0
  "@platforma-sdk/eslint-config": ^1.0.1
  "@milaboratories/graph-maker": ^1.1.44

  '@milaboratories/software-pframes-conv': ^2.1.7
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.13
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.5
  
  "vue": ^3.5.12
  "vue-tsc": ^2.1.6
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.2.3

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.28.1
