packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.22.59
  "@platforma-sdk/ui-vue": ^1.22.64
  "@platforma-sdk/workflow-tengo": ^2.15.1
  "@platforma-sdk/block-tools": ^2.5.17
  "@platforma-sdk/test": ^1.22.76
  "@platforma-sdk/tengo-builder": ^1.19.1
  "@platforma-sdk/package-builder": ^2.15.4
  "@platforma-sdk/eslint-config": ^1.0.1
  "@milaboratories/graph-maker": ^1.1.51

  '@milaboratories/software-pframes-conv': ^2.1.16
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.13
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.28.1
